### ISSUE TITLE
How should one run the `script_pytype_type_infer.py` script?

### ISSUE THREAD

**Issue by jose** [mlcodepatterns/PythonTypeInformation#1]
Hi,

Quick couple of questions,
1. How should one run the [`script_pytype_type_infer.py`](https://github.com/mlcodepatterns/PythonTypeInformation/blob/master/script_pytype_type_infer.py) script?  I can see in [here](https://github.com/mlcodepatterns/PythonTypeInformation/blob/master/script_pytype_type_infer.py#L90) that it expects 4 arguments but I've no clue what those should be or in which format should be.  Please provide more details on that.
2. And, what are the requirements to run the script, i.e., Python version, dependencies, etc?

--
Best,
Jose

**Comment by maldil** [comment]
Thank you for the questions. Please see the https://github.com/mlcodepatterns/PythonTypeInformation/blob/master/README.md#infer-type-information-of-new-projects

**Comment by jose** [comment]
Thanks for updating that documentation.  However, I haven't yet managed to run it successfully:

```
$ python3.8 script_pytype_type_infer.py ./Pytypestorage/ ./GitHub/ ./TYPE_REPO/ nltk/nltk https://github.com/nltk/nltk.git
Repo is downloading to :./GitHub//nltk/nltk
before b0e85694107992e00a2f9fb48e6410c50fe1f1f6
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "script_pytype_type_infer.py", line 205, in process_before_change
    first_rev = generate_type_info(file_path, project_path, mod.new_path.replace('/', '.'), save_name,
  File "script_pytype_type_infer.py", line 214, in generate_type_info
    generate_pytype_folder(project_path, file_path, pytype_storage, type_repo)
  File "script_pytype_type_infer.py", line 64, in generate_pytype_folder
    subprocess.run(['pytype', '--pythonpath=' + project_path, '--python-version=' + py_version_s, '--no-report-errors',
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pytype'
after b0e85694107992e00a2f9fb48e6410c50fe1f1f6
Process Process-3:
...
```

My system:
```
$ python3 --version
Python 3.8.10

$ echo $PATH
/home/jcmcampos/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

$ echo $PYTHONPATH
/home/jcmcampos/.local/lib/python3.8/site-packages
```

**Comment by maldil** [comment]
I am trying to figure out the error. Did you run this command in a Python virtual environment as instructed in https://github.com/mlcodepatterns/PythonTypeInformation#infer-type-information-of-new-projects? According to PyType manual, it is OS dependent. Can you please confirm your OS ?
Please see https://github.com/google/pytype#requirements

**Comment by jose** [comment]
> I am trying to figure out the error. 

The error seems to be in [here](https://github.com/mlcodepatterns/PythonTypeInformation/blob/master/script_pytype_type_infer.py#L64).

> Did you run this command in a Python virtual environment as instructed in https://github.com/mlcodepatterns/PythonTypeInformation#infer-type-information-of-new-projects?

I didn't run `python3.7 -m venv ./VENV` (to create new virtual environment) and neither run `source VENV/bin/activate` (to activate the virtual environment) because I think it's pointless.  I did however run `pip install -r requirements.txt` to install all required dependencies.

> According to PyType manual, it is OS dependent. Can you please confirm your OS ? Please see https://github.com/google/pytype#requirements

I'm on Linux, more specifically Ubuntu 20.04.1 LTS.

**Comment by maldil** [comment]
This occurs because the subprocess is unable to locate the `pytype` binaries. To run pytype, the API `subprocess.run` copies the current Python environment, therefore pytype must be installed in the copying environment. 

https://github.com/mlcodepatterns/PythonTypeInformation/blob/1faa172ce95e51962fc0b0095b84064ea1437a54/script_pytype_type_infer.py#L63

I tried it in virtual environments, which generally let me create isolated working settings devoid of extraneous side effects and usually path problems are rare.

Another thing, `pytype` depends on Python version. If the users Python version is different, he can create a virtual environment with the desired Python version. This script is configured to work on Python 3.7. https://github.com/mlcodepatterns/PythonTypeInformation/blob/1faa172ce95e51962fc0b0095b84064ea1437a54/script_pytype_type_infer.py#L24

https://github.com/mlcodepatterns/PythonTypeInformation/blob/1faa172ce95e51962fc0b0095b84064ea1437a54/script_pytype_type_infer.py#L25

**Comment by jose** [comment]
Adapting the script to Python 3.8 did the trick, i.e., modifying lines [24](https://github.com/mlcodepatterns/PythonTypeInformation/blob/master/script_pytype_type_infer.py#L24) and [25](https://github.com/mlcodepatterns/PythonTypeInformation/blob/master/script_pytype_type_infer.py#L25) to `py_version_s = '3.8'` and `py_version = (3, 8)`, respectively.
